name: frontend
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_route: ^0.6.9
  cloud_firestore: ^0.14.0+2
  dartz: ^0.9.1
  flushbar: ^1.10.4
  flutter_bloc: ^6.0.1
  flutter_hooks: ^0.13.0
  flutter_slidable: ^0.5.7
  freezed_annotation: ^0.12.0
  get_it: ^4.0.4
  implicitly_animated_reorderable_list: ^0.3.0
  injectable: ^1.0.4
  json_annotation: ^3.0.1
  kt_dart: ^0.7.0+1
  provider: ^4.3.2+2
  rxdart: ^0.24.1
  uuid: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.6.10
  build_runner: null
  freezed: ^0.12.2
  injectable_generator: ^1.0.4
  json_serializable: ^3.3.0
  lint: ^1.2.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
